# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Matthew<br>Moore<br>Kling
tagline:          'macroecology'
description:      "<br>WARNING: SITE UNDER CONSTRUCTION<br><br>I'm a Berkeley PhD student studying biodiversity, climate change, & ecoinformatics"
url:              http://matthewkling.github.io
baseurl:          /

author:
  name:           'Matthew Kling'
  url:            http://matthewkling.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Gems
gems: [jekyll-paginate, jekyll-gist]