# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Matthew Kling
tagline:          'Tagline'
description:      '[site under construction]'
url:              http://matthewkling.github.io
baseurl:          /

author:
  name:           'Matthew Kling'
  url:            http://matthewkling.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Gems
gems: [jekyll-paginate, jekyll-gist]