# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Matthew Kling
tagline:          'biodiversity & climate change'
description:      "<br>I'm a Berkeley PhD student studying<br>spatial biodiversity, climate change & ecoinformatics"
url:              http://matthewkling.github.io
baseurl:          /

author:
  name:           'Matthew Kling'
  url:            http://matthewkling.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           

# Gems
gems: [jekyll-paginate, jekyll-gist]