baseurl = "https://example.org/"
title = "Matthew Kling"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-77357249-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Macroecology & global change"
  copyright = "&copy;2022 Matthew Kling"
  sidebarAbout = [
    "I'm an ecologist and data scientist focused on understanding biodiversity patterns and informing conservation under global environmental change. I conduct empirical research, develop modeling tools, and create data visualizations. I am currently a postdoctoral fellow at UVM."
  ]

  email = "mkling@uvm.edu"

  # Nav links in the side bar
  # (Have to edit content/ and themes//layouts to create these pages)
  
  [[params.navlinks]]
  name = "Work"
  url = "media/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "CV"
  url = "cv/"
  
  [[params.navlinks]]
  name = "Contact"
  url = "contact/"

  [params.social]
  email         = "mkling@uvm.edu"
  twitter       = "full profile url in twitter"
  github        = "https://github.com/matthewkling"
